using atelier_platform_aplicaciones_web.IoT.Domain.Model.ValueObjects;

namespace atelier_platform_aplicaciones_web.IoT.Domain.Model.Queries;

public record GetDtcAlertsByRegistrationIdQuery(Obd2DeviceRegistrationId RegistrationId);
