using atelier_platform_aplicaciones_web.Core.Domain.Model.ValueObjects;

namespace atelier_platform_aplicaciones_web.IoT.Domain.Model.Queries;

public record GetEmployeeRegistrationByEmployeeIdQuery(EmployeeId EmployeeId);