using atelier_platform_aplicaciones_web.IoT.Domain.Model.ValueObjects;

namespace atelier_platform_aplicaciones_web.IoT.Domain.Model.Commands;

public record DeactivateObd2DeviceRegistrationCommand(Obd2DeviceRegistrationId RegistrationId);
